"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var point1 = new point_1.Point(-155, -250);
console.log(point1.toString());
console.log(point1.distanceToOrigin());
console.log(point1.calcularDistancia(point1));
console.log(point1.calculateQuadrant());
var point2 = new point_1.Point(808, 56);
var point3 = new point_1.Point(357, 159);
var point4 = new point_1.Point(753, 654);
var point5 = new point_1.Point(729, 183);
